apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  labels:
    app : jenkins-slave
spec:
  containers:
  - name: jenkins-slave
    image: bitnami/kubectl
    tty: true
    imagePullPolicy: Always
    env:
    - name: JENKINS_URL
      value: http://192.168.0.140:8080
    command:
      - /bin/sh
    volumeMounts:
    - name: dockersock
      mountPath: "/var/run/docker.sock"
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
