apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  labels:
    app : jenkins-slave
spec:
  containers:
  - name: jenkins-slave
    image: 827461279864.dkr.ecr.sa-east-1.amazonaws.com/jenkins.devops:latest
    tty: true
    imagePullPolicy: Always
    command:
      - /bin/sh
    volumeMounts:
    - name: dockersock
      mountPath: "/var/run/docker.sock"
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
